// <auto-generated />
using System;
using Customer_Managerment.CustomerManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Customer_Managerment.Data.Migrations
{
    [DbContext(typeof(CustomerManagementDbContext))]
    [Migration("20260514190935_AddTeamAssignment")]
    partial class AddTeamAssignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("IdContact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_contact")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("IdLead")
                        .HasColumnType("uuid")
                        .HasColumnName("id_lead");

                    b.Property<Guid>("IdStaff")
                        .HasColumnType("uuid")
                        .HasColumnName("id_staff");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdContact")
                        .HasName("contact_pkey");

                    b.HasIndex("IdLead");

                    b.HasIndex("IdStaff");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.Deal", b =>
                {
                    b.Property<Guid>("IdDeal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_deal")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("IdCustomer")
                        .HasColumnType("uuid")
                        .HasColumnName("id_customer");

                    b.Property<Guid>("IdStaff")
                        .HasColumnType("uuid")
                        .HasColumnName("id_staff");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdDeal")
                        .HasName("deal_pkey");

                    b.HasIndex("IdCustomer");

                    b.HasIndex("IdStaff");

                    b.ToTable("deals", (string)null);
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("IdNote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_note")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("IdStaff")
                        .HasColumnType("uuid")
                        .HasColumnName("id_staff");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pinned");

                    b.Property<Guid>("LinkedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_entity_id");

                    b.Property<string>("LinkedEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("linked_entity_type");

                    b.Property<Guid?>("ParentNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_note_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdNote")
                        .HasName("note_pkey");

                    b.HasIndex("ParentNoteId");

                    b.HasIndex(new[] { "LinkedEntityType", "LinkedEntityId" }, "ix_notes_entity");

                    b.HasIndex(new[] { "IdStaff" }, "ix_notes_id_staff");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.NoteMention", b =>
                {
                    b.Property<Guid>("IdMention")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_mention")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IdNote")
                        .HasColumnType("uuid")
                        .HasColumnName("id_note");

                    b.Property<Guid>("IdStaffMentioned")
                        .HasColumnType("uuid")
                        .HasColumnName("id_staff_mentioned");

                    b.HasKey("IdMention")
                        .HasName("note_mention_pkey");

                    b.HasIndex(new[] { "IdNote" }, "ix_note_mentions_id_note");

                    b.HasIndex(new[] { "IdStaffMentioned" }, "ix_note_mentions_id_staff_mentioned");

                    b.ToTable("note_mentions", (string)null);
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_notification")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IdStaff")
                        .HasColumnType("uuid")
                        .HasColumnName("id_staff");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pinned");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("related_entity_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("IdNotification")
                        .HasName("notification_pkey");

                    b.HasIndex(new[] { "IdStaff" }, "ix_notifications_id_staff");

                    b.HasIndex(new[] { "IdStaff", "IsRead" }, "ix_notifications_id_staff_is_read");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Discriminator")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("discriminator");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fullname");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_active_at");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Resource")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resource");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<decimal?>("Salary")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("salary");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("person_pkey");

                    b.HasIndex(new[] { "Email" }, "persons_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "persons_username_key")
                        .IsUnique();

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.StaffActivityLog", b =>
                {
                    b.Property<Guid>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_log")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("IdStaff")
                        .HasColumnType("uuid")
                        .HasColumnName("id_staff");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("IdLog")
                        .HasName("staff_activity_log_pkey");

                    b.HasIndex(new[] { "IdStaff" }, "ix_staff_activity_logs_id_staff");

                    b.HasIndex(new[] { "Timestamp" }, "ix_staff_activity_logs_timestamp");

                    b.ToTable("staff_activity_logs", (string)null);
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("IdTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_task")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("due_date");

                    b.Property<Guid>("IdStaffAssigned")
                        .HasColumnType("uuid")
                        .HasColumnName("id_staff_assigned");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("LinkedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_entity_id");

                    b.Property<string>("LinkedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("linked_entity_type");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdTask")
                        .HasName("task_pkey");

                    b.HasIndex(new[] { "IdStaffAssigned" }, "ix_tasks_id_staff_assigned");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("assigned_by");

                    b.Property<bool>("CanDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_delete");

                    b.Property<bool>("CanEdit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_edit");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("IdStaff")
                        .HasColumnType("uuid")
                        .HasColumnName("id_staff");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("team_member_pkey");

                    b.HasIndex(new[] { "EntityType", "EntityId" }, "ix_team_members_entity");

                    b.HasIndex(new[] { "IdStaff" }, "ix_team_members_id_staff");

                    b.ToTable("team_members", (string)null);
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.Contact", b =>
                {
                    b.HasOne("Customer_Managerment.CustomerManagement.Domain.Entities.Person", "IdLeadNavigation")
                        .WithMany()
                        .HasForeignKey("IdLead")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contact_lead");

                    b.HasOne("Customer_Managerment.CustomerManagement.Domain.Entities.Person", "IdStaffNavigation")
                        .WithMany("Contacts")
                        .HasForeignKey("IdStaff")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contact_staff");

                    b.Navigation("IdLeadNavigation");

                    b.Navigation("IdStaffNavigation");
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.Deal", b =>
                {
                    b.HasOne("Customer_Managerment.CustomerManagement.Domain.Entities.Person", "IdCustomerNavigation")
                        .WithMany()
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deal_customer");

                    b.HasOne("Customer_Managerment.CustomerManagement.Domain.Entities.Person", "IdStaffNavigation")
                        .WithMany("Deals")
                        .HasForeignKey("IdStaff")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deal_staff");

                    b.Navigation("IdCustomerNavigation");

                    b.Navigation("IdStaffNavigation");
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.Note", b =>
                {
                    b.HasOne("Customer_Managerment.CustomerManagement.Domain.Entities.Person", "IdStaffNavigation")
                        .WithMany()
                        .HasForeignKey("IdStaff")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_note_staff");

                    b.HasOne("Customer_Managerment.CustomerManagement.Domain.Entities.Note", "ParentNote")
                        .WithMany("Replies")
                        .HasForeignKey("ParentNoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_note_parent");

                    b.Navigation("IdStaffNavigation");

                    b.Navigation("ParentNote");
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.NoteMention", b =>
                {
                    b.HasOne("Customer_Managerment.CustomerManagement.Domain.Entities.Note", "IdNoteNavigation")
                        .WithMany("Mentions")
                        .HasForeignKey("IdNote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_note_mention_note");

                    b.HasOne("Customer_Managerment.CustomerManagement.Domain.Entities.Person", "IdStaffMentionedNavigation")
                        .WithMany()
                        .HasForeignKey("IdStaffMentioned")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_note_mention_staff");

                    b.Navigation("IdNoteNavigation");

                    b.Navigation("IdStaffMentionedNavigation");
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Customer_Managerment.CustomerManagement.Domain.Entities.Person", "IdStaffNavigation")
                        .WithMany()
                        .HasForeignKey("IdStaff")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_staff");

                    b.Navigation("IdStaffNavigation");
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.StaffActivityLog", b =>
                {
                    b.HasOne("Customer_Managerment.CustomerManagement.Domain.Entities.Person", "IdStaffNavigation")
                        .WithMany()
                        .HasForeignKey("IdStaff")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_activity_log_staff");

                    b.Navigation("IdStaffNavigation");
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.TaskEntity", b =>
                {
                    b.HasOne("Customer_Managerment.CustomerManagement.Domain.Entities.Person", "IdStaffAssignedNavigation")
                        .WithMany()
                        .HasForeignKey("IdStaffAssigned")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_staff");

                    b.Navigation("IdStaffAssignedNavigation");
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("Customer_Managerment.CustomerManagement.Domain.Entities.Person", "IdStaffNavigation")
                        .WithMany()
                        .HasForeignKey("IdStaff")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_member_staff");

                    b.Navigation("IdStaffNavigation");
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.Note", b =>
                {
                    b.Navigation("Mentions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Customer_Managerment.CustomerManagement.Domain.Entities.Person", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Deals");
                });
#pragma warning restore 612, 618
        }
    }
}
